/**
 * DrawingML preset shape adjust-guide names from ECMA-376 Fourth Edition,
 * Part 1 Annex D (`OfficeOpenXML-DrawingMLGeometries.zip` /
 * `presetShapeDefinitions.xml`). The PDF corpus does not include this addendum.
 *
 * Every ST_ShapeType value is included so callers can distinguish a valid
 * shape with no guides from an invalid shape name.
 */
const PRESET_SHAPES = new Map<string, readonly string[]>([
	["line", []],
	["lineInv", []],
	["triangle", ["adj"]],
	["rtTriangle", []],
	["rect", []],
	["diamond", []],
	["parallelogram", ["adj"]],
	["trapezoid", ["adj"]],
	["nonIsoscelesTrapezoid", ["adj1", "adj2"]],
	["pentagon", ["hf", "vf"]],
	["hexagon", ["adj", "vf"]],
	["heptagon", ["hf", "vf"]],
	["octagon", ["adj"]],
	["decagon", ["vf"]],
	["dodecagon", []],
	["star4", ["adj"]],
	["star5", ["adj", "hf", "vf"]],
	["star6", ["adj", "hf"]],
	["star7", ["adj", "hf", "vf"]],
	["star8", ["adj"]],
	["star10", ["adj", "hf"]],
	["star12", ["adj"]],
	["star16", ["adj"]],
	["star24", ["adj"]],
	["star32", ["adj"]],
	["roundRect", ["adj"]],
	["round1Rect", ["adj"]],
	["round2SameRect", ["adj1", "adj2"]],
	["round2DiagRect", ["adj1", "adj2"]],
	["snipRoundRect", ["adj1", "adj2"]],
	["snip1Rect", ["adj"]],
	["snip2SameRect", ["adj1", "adj2"]],
	["snip2DiagRect", ["adj1", "adj2"]],
	["plaque", ["adj"]],
	["ellipse", []],
	["teardrop", ["adj"]],
	["homePlate", ["adj"]],
	["chevron", ["adj"]],
	["pieWedge", []],
	["pie", ["adj1", "adj2"]],
	["blockArc", ["adj1", "adj2", "adj3"]],
	["donut", ["adj"]],
	["noSmoking", ["adj"]],
	["rightArrow", ["adj1", "adj2"]],
	["leftArrow", ["adj1", "adj2"]],
	// The fourth-edition addendum duplicates upDownArrow where upArrow belongs;
	// ST_ShapeType and the corresponding reference implementation confirm these guides.
	["upArrow", ["adj1", "adj2"]],
	["downArrow", ["adj1", "adj2"]],
	["stripedRightArrow", ["adj1", "adj2"]],
	["notchedRightArrow", ["adj1", "adj2"]],
	["bentUpArrow", ["adj1", "adj2", "adj3"]],
	["leftRightArrow", ["adj1", "adj2"]],
	["upDownArrow", ["adj1", "adj2"]],
	["leftUpArrow", ["adj1", "adj2", "adj3"]],
	["leftRightUpArrow", ["adj1", "adj2", "adj3"]],
	["quadArrow", ["adj1", "adj2", "adj3"]],
	["leftArrowCallout", ["adj1", "adj2", "adj3", "adj4"]],
	["rightArrowCallout", ["adj1", "adj2", "adj3", "adj4"]],
	["upArrowCallout", ["adj1", "adj2", "adj3", "adj4"]],
	["downArrowCallout", ["adj1", "adj2", "adj3", "adj4"]],
	["leftRightArrowCallout", ["adj1", "adj2", "adj3", "adj4"]],
	["upDownArrowCallout", ["adj1", "adj2", "adj3", "adj4"]],
	["quadArrowCallout", ["adj1", "adj2", "adj3", "adj4"]],
	["bentArrow", ["adj1", "adj2", "adj3", "adj4"]],
	["uturnArrow", ["adj1", "adj2", "adj3", "adj4", "adj5"]],
	["circularArrow", ["adj1", "adj2", "adj3", "adj4", "adj5"]],
	["leftCircularArrow", ["adj1", "adj2", "adj3", "adj4", "adj5"]],
	["leftRightCircularArrow", ["adj1", "adj2", "adj3", "adj4", "adj5"]],
	["curvedRightArrow", ["adj1", "adj2", "adj3"]],
	["curvedLeftArrow", ["adj1", "adj2", "adj3"]],
	["curvedUpArrow", ["adj1", "adj2", "adj3"]],
	["curvedDownArrow", ["adj1", "adj2", "adj3"]],
	["swooshArrow", ["adj1", "adj2"]],
	["cube", ["adj"]],
	["can", ["adj"]],
	["lightningBolt", []],
	["heart", []],
	["sun", ["adj"]],
	["moon", ["adj"]],
	["smileyFace", ["adj"]],
	["irregularSeal1", []],
	["irregularSeal2", []],
	["foldedCorner", ["adj"]],
	["bevel", ["adj"]],
	["frame", ["adj1"]],
	["halfFrame", ["adj1", "adj2"]],
	["corner", ["adj1", "adj2"]],
	["diagStripe", ["adj"]],
	["chord", ["adj1", "adj2"]],
	["arc", ["adj1", "adj2"]],
	["leftBracket", ["adj"]],
	["rightBracket", ["adj"]],
	["leftBrace", ["adj1", "adj2"]],
	["rightBrace", ["adj1", "adj2"]],
	["bracketPair", ["adj"]],
	["bracePair", ["adj"]],
	["straightConnector1", []],
	["bentConnector2", []],
	["bentConnector3", ["adj1"]],
	["bentConnector4", ["adj1", "adj2"]],
	["bentConnector5", ["adj1", "adj2", "adj3"]],
	["curvedConnector2", []],
	["curvedConnector3", ["adj1"]],
	["curvedConnector4", ["adj1", "adj2"]],
	["curvedConnector5", ["adj1", "adj2", "adj3"]],
	["callout1", ["adj1", "adj2", "adj3", "adj4"]],
	["callout2", ["adj1", "adj2", "adj3", "adj4", "adj5", "adj6"]],
	["callout3", ["adj1", "adj2", "adj3", "adj4", "adj5", "adj6", "adj7", "adj8"]],
	["accentCallout1", ["adj1", "adj2", "adj3", "adj4"]],
	["accentCallout2", ["adj1", "adj2", "adj3", "adj4", "adj5", "adj6"]],
	["accentCallout3", ["adj1", "adj2", "adj3", "adj4", "adj5", "adj6", "adj7", "adj8"]],
	["borderCallout1", ["adj1", "adj2", "adj3", "adj4"]],
	["borderCallout2", ["adj1", "adj2", "adj3", "adj4", "adj5", "adj6"]],
	["borderCallout3", ["adj1", "adj2", "adj3", "adj4", "adj5", "adj6", "adj7", "adj8"]],
	["accentBorderCallout1", ["adj1", "adj2", "adj3", "adj4"]],
	["accentBorderCallout2", ["adj1", "adj2", "adj3", "adj4", "adj5", "adj6"]],
	["accentBorderCallout3", ["adj1", "adj2", "adj3", "adj4", "adj5", "adj6", "adj7", "adj8"]],
	["wedgeRectCallout", ["adj1", "adj2"]],
	["wedgeRoundRectCallout", ["adj1", "adj2", "adj3"]],
	["wedgeEllipseCallout", ["adj1", "adj2"]],
	["cloudCallout", ["adj1", "adj2"]],
	["cloud", []],
	["ribbon", ["adj1", "adj2"]],
	["ribbon2", ["adj1", "adj2"]],
	["ellipseRibbon", ["adj1", "adj2", "adj3"]],
	["ellipseRibbon2", ["adj1", "adj2", "adj3"]],
	["leftRightRibbon", ["adj1", "adj2", "adj3"]],
	["verticalScroll", ["adj"]],
	["horizontalScroll", ["adj"]],
	["wave", ["adj1", "adj2"]],
	["doubleWave", ["adj1", "adj2"]],
	["plus", ["adj"]],
	["flowChartProcess", []],
	["flowChartDecision", []],
	["flowChartInputOutput", []],
	["flowChartPredefinedProcess", []],
	["flowChartInternalStorage", []],
	["flowChartDocument", []],
	["flowChartMultidocument", []],
	["flowChartTerminator", []],
	["flowChartPreparation", []],
	["flowChartManualInput", []],
	["flowChartManualOperation", []],
	["flowChartConnector", []],
	["flowChartPunchedCard", []],
	["flowChartPunchedTape", []],
	["flowChartSummingJunction", []],
	["flowChartOr", []],
	["flowChartCollate", []],
	["flowChartSort", []],
	["flowChartExtract", []],
	["flowChartMerge", []],
	["flowChartOfflineStorage", []],
	["flowChartOnlineStorage", []],
	["flowChartMagneticTape", []],
	["flowChartMagneticDisk", []],
	["flowChartMagneticDrum", []],
	["flowChartDisplay", []],
	["flowChartDelay", []],
	["flowChartAlternateProcess", []],
	["flowChartOffpageConnector", []],
	["actionButtonBlank", []],
	["actionButtonHome", []],
	["actionButtonHelp", []],
	["actionButtonInformation", []],
	["actionButtonForwardNext", []],
	["actionButtonBackPrevious", []],
	["actionButtonEnd", []],
	["actionButtonBeginning", []],
	["actionButtonReturn", []],
	["actionButtonDocument", []],
	["actionButtonSound", []],
	["actionButtonMovie", []],
	["gear6", ["adj1", "adj2"]],
	["gear9", ["adj1", "adj2"]],
	["funnel", []],
	["mathPlus", ["adj1"]],
	["mathMinus", ["adj1"]],
	["mathMultiply", ["adj1"]],
	["mathDivide", ["adj1", "adj2", "adj3"]],
	["mathEqual", ["adj1", "adj2"]],
	["mathNotEqual", ["adj1", "adj2", "adj3"]],
	["cornerTabs", []],
	["squareTabs", []],
	["plaqueTabs", []],
	["chartX", []],
	["chartStar", []],
	["chartPlus", []],
]);

export function lookupPresetShapeGuides(shape: string): readonly string[] | null {
	return PRESET_SHAPES.get(shape) ?? null;
}
