/**
 * Generate the MCP preset-shape lookup from ECMA-376 Part 1 Annex D.
 *
 * By default, the script downloads the pinned fourth-edition archive from
 * data/sources.json and extracts presetShapeDefinitions.xml from its nested
 * ZIP files. Pass --source to regenerate from an already extracted XML file.
 */

import { createHash } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, join } from "node:path";
import { XMLParser } from "fast-xml-parser";

const SOURCE_NAME = "ecma-376-annex-d-drawingml-geometries";
const OUTPUT_PATH = "apps/mcp-server/src/preset-shape-guides.generated.ts";
const PART_1_ZIP =
	"ECMA-376, Fourth Edition, Part 1 - Fundamentals And Markup Language Reference.zip";
const GEOMETRIES_ZIP = "OfficeOpenXML-DrawingMLGeometries.zip";
const SHAPES_XML = "presetShapeDefinitions.xml";

interface SourceEntry {
	name: string;
	url: string;
	sha256: string;
}

interface SourceManifest {
	sources: SourceEntry[];
}

type PreserveOrderNode = Record<string, unknown>;

export interface PresetShapeGuides {
	name: string;
	guides: string[];
}

export function extractPresetShapeGuides(xml: string): PresetShapeGuides[] {
	const parsed = new XMLParser({ preserveOrder: true, ignoreAttributes: false }).parse(
		xml,
	) as PreserveOrderNode[];
	const documentRoot = parsed.find((node) => Array.isArray(node.presetShapeDefinitons));
	const shapeNodes = documentRoot?.presetShapeDefinitons as PreserveOrderNode[] | undefined;
	if (!shapeNodes) throw new Error("presetShapeDefinitons root not found");

	const shapes = new Map<string, string[]>();
	for (const shapeNode of shapeNodes) {
		const name = Object.keys(shapeNode).find((key) => key !== ":@");
		if (!name) continue;

		const contents = shapeNode[name] as PreserveOrderNode[];
		const avList = contents.find((node) => Array.isArray(node.avLst))?.avLst as
			| PreserveOrderNode[]
			| undefined;
		const guides = (avList ?? [])
			.filter((node) => Array.isArray(node.gd))
			.map((node) => (node[":@"] as Record<string, string> | undefined)?.["@_name"])
			.filter((guide): guide is string => typeof guide === "string");

		const existing = shapes.get(name);
		if (existing) {
			if (existing.join("\0") !== guides.join("\0")) {
				throw new Error(`Conflicting Annex D definitions for ${name}`);
			}
			continue;
		}
		shapes.set(name, guides);
	}

	if (shapes.size === 0) throw new Error("No preset shapes found in Annex D");
	return [...shapes].map(([name, guides]) => ({ name, guides }));
}

function sha256(data: ArrayBuffer | Uint8Array | string): string {
	return createHash("sha256").update(data).digest("hex");
}

async function extractZipEntry(
	zipPath: string,
	entry: string,
	destination: string,
): Promise<string> {
	const process = Bun.spawn(["unzip", "-j", "-o", "-q", zipPath, entry, "-d", destination], {
		stdout: "inherit",
		stderr: "pipe",
	});
	const [error, code] = await Promise.all([new Response(process.stderr).text(), process.exited]);
	if (code !== 0) throw new Error(`Could not extract ${entry}: ${error.trim()}`);
	return join(destination, basename(entry));
}

async function downloadAnnexXml(): Promise<Uint8Array> {
	const manifest = (await Bun.file("data/sources.json").json()) as SourceManifest;
	const source = manifest.sources.find((entry) => entry.name === SOURCE_NAME);
	if (!source) throw new Error(`Missing ${SOURCE_NAME} in data/sources.json`);

	const response = await fetch(source.url);
	if (!response.ok) throw new Error(`Could not download Annex D: ${response.status}`);
	const outerZip = new Uint8Array(await response.arrayBuffer());
	const actualHash = sha256(outerZip);
	if (actualHash !== source.sha256) {
		throw new Error(`Annex D source hash mismatch: expected ${source.sha256}, got ${actualHash}`);
	}

	const tempDirectory = await mkdtemp(join(tmpdir(), "ooxml-annex-d-"));
	try {
		const outerPath = join(tempDirectory, "edition4.zip");
		await Bun.write(outerPath, outerZip);
		const part1Path = await extractZipEntry(outerPath, PART_1_ZIP, tempDirectory);
		const geometriesPath = await extractZipEntry(part1Path, GEOMETRIES_ZIP, tempDirectory);
		const shapesPath = await extractZipEntry(geometriesPath, SHAPES_XML, tempDirectory);
		return new Uint8Array(await Bun.file(shapesPath).arrayBuffer());
	} finally {
		await rm(tempDirectory, { recursive: true, force: true });
	}
}

function renderLookup(shapes: PresetShapeGuides[], sourceHash: string): string {
	const entries = shapes
		.map(({ name, guides }) => `\t[${JSON.stringify(name)}, ${JSON.stringify(guides)}],`)
		.join("\n");
	return `/**
 * Generated by scripts/generate-preset-shape-guides.ts.
 * Source: ECMA-376 Fourth Edition, Part 1 Annex D, presetShapeDefinitions.xml
 * Source XML SHA-256: ${sourceHash}
 * Do not edit by hand.
 */
const PRESET_SHAPES = new Map<string, readonly string[]>([
${entries}
]);

export function lookupPresetShapeGuides(shape: string): readonly string[] | null {
\treturn PRESET_SHAPES.get(shape) ?? null;
}
`;
}

function sourceArgument(): string | null {
	const index = process.argv.indexOf("--source");
	return index === -1 ? null : (process.argv[index + 1] ?? null);
}

async function main() {
	const source = sourceArgument();
	if (process.argv.includes("--source") && !source)
		throw new Error("--source requires an XML path");

	const xmlBytes = source
		? new Uint8Array(await Bun.file(source).arrayBuffer())
		: await downloadAnnexXml();
	const xml = new TextDecoder().decode(xmlBytes);
	const shapes = extractPresetShapeGuides(xml);
	await Bun.write(OUTPUT_PATH, renderLookup(shapes, sha256(xmlBytes)));

	const format = Bun.spawn(["bunx", "biome", "format", "--write", OUTPUT_PATH], {
		stdout: "inherit",
		stderr: "inherit",
	});
	if ((await format.exited) !== 0) throw new Error("Could not format generated lookup");
	console.log(`Generated ${OUTPUT_PATH} from ${shapes.length} Annex D shapes.`);
}

if (import.meta.main) {
	main().catch((error) => {
		console.error(error instanceof Error ? error.message : error);
		process.exit(1);
	});
}
